name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1.1.0
    - uses: actions/checkout@master
    - name: Cleanup
      run: rm -rf ~/.npm
    - name: Cleanup 2
      run: npm cache clean --force
    - name: Cleanup 3
      run: rm -rf node_modules package-lock.json
    - name: Install packages
      run: npm install --no-bin-links
    - run: mkdir -p build/release
    - name: build service
      run: npm run build
    - name: Get tag
      run: echo "::set-env name=SVC_VERSION::$(cat package.json | jq -r .version)"
    - name: check
      run: echo "SVC_VERSION = $SVC_VERSION"
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: frogfishio/user
        username: frogfishio
        password: ${{ secrets.DOCKERHUB_SECRET }}
        tags: "latest,${{ env.SVC_VERSION }}"
